---
- hosts: local
  
  vars:
    - user_name: chrish
  tasks:
    - name: Install common softwares
      apt: pkg={{ item }} state=installed
      with_items:
        - git
        - htop
        - vim
        - unzip
        - curl
        - sudo
        - zsh

    - name: Create a sudo group
      group:
        name=sudo
        state=present

    - name: create a new user
      user:
        name={{ user_name }}
        state=present
        groups="sudo"
        shell=/bin/zsh
        password=sunhar143

    - name: create home directory folder structure
      file: path=/home/{{ user_name }}/{{ item }}
        state=directory
        owner={{ user_name }}
        group={{ user_name }}
        mode=0700
      with_items:
        - src
        - backups
        - bin
        - tmp